accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from django.urls import reverse_lazy

from . import views


urlpatterns = [
    path('login/', views.UserLoginView.as_view(),name='login'),
    path('logout/',
        LogoutView.as_view(next_page=reverse_lazy('accounts:login')),
        name='logout'),
    path(
        'create-profile/',
        views.CreateProfileView.as_view(), name='create-profile'),
    path(
        'edit-profile/',
        views.UpdateProfileView.as_view(), name='edit-profile'),
    path('my-profile/', views.MyProfileView.as_view(), name='my-profile'),
    path('profile/<slug:slug>/', views.ProfileView.as_view(), name='profile'),
    path('register/', views.RegisterView.as_view(), name='register'),
]

posts/urls.py
from django.urls import path
from django.urls import reverse_lazy

from . import views


urlpatterns = [
    path('create/',
        views.PostCreateView.as_view(),name='create-post'),
]

social_media/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic.base import TemplateView

from rest_framework import routers


router = routers.DefaultRouter()

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='home'),
    path('accounts/',
        include(('accounts.urls', 'accounts'), namespace="accounts")),
    path('comments/',
        include(('comments.urls', 'comments'), namespace="comments")),
    path('newsfeeds/',
        include(('newsfeeds.urls', 'newsfeeds'), namespace="newsfeeds")),
    path('posts/',
        include(('posts.urls', 'posts'), namespace="posts")),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('activity/', include('actstream.urls')),

    # DRF URLs
    path('', include('comments.urls_api')),
    path('', include('accounts.urls_api')),
    path('', include('posts.urls_api')),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]


if settings.DEBUG:
    urlpatterns = (
        urlpatterns + static(
            settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock %}

{% block css %}
.card {
    margin-top: 110px;
    margin-left: auto;
    margin-right: auto;
    border-radius: 5%;
    -moz-border-radius: 5%;
    -webkit-border-radius: 5%;
}
{% endblock css %}

{% block content %}
<div class="row">
    <div class="card col-lg-3 col-md-4 col-sm-12 col-12">
        <img class="card-img-top" src="{% static 'stainlesstalong.png' %}" alt="Site Profile">
        <div class="card-body">
            <h5 class="card-title">Stainless Talong</h5>
            <p class="card-text">Already have an account? Login <a href="{% url 'accounts:login' %}" class="card-link">here</a>.</p>
            <p class="card-text">Wanna join the fun? Register <a href="{% url 'accounts:register' %}" class="card-link">here</a>.</p>
        </div>
    </div>
</div>
{% endblock content %}