accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from django.urls import reverse_lazy

from . import views


urlpatterns = [
    path('login/', views.UserLoginView.as_view(),name='login'),
    path('logout/',
        LogoutView.as_view(next_page=reverse_lazy('accounts:login')),
        name='logout'),
    path(
        'create-profile/',
        views.CreateProfileView.as_view(), name='create-profile'),
    path(
        'edit-profile/',
        views.UpdateProfileView.as_view(), name='edit-profile'),
    path('my-profile/', views.MyProfileView.as_view(), name='my-profile'),
    path('profile/<slug:slug>/', views.ProfileView.as_view(), name='profile'),
    path('register/', views.RegisterView.as_view(), name='register'),
]

newsfeeds/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('',
        views.NewsFeedListView.as_view(),name='list'),
]

posts/urls.py
from django.urls import path
from django.urls import reverse_lazy

from . import views


urlpatterns = [
    path('create/',
        views.PostCreateView.as_view(),name='create-post'),
]

social_media/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic.base import TemplateView

from rest_framework import routers


router = routers.DefaultRouter()

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='home'),
    path('accounts/',
        include(('accounts.urls', 'accounts'), namespace="accounts")),
    path('comments/',
        include(('comments.urls', 'comments'), namespace="comments")),
    path('newsfeeds/',
        include(('newsfeeds.urls', 'newsfeeds'), namespace="newsfeeds")),
    path('posts/',
        include(('posts.urls', 'posts'), namespace="posts")),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('activity/', include('actstream.urls')),

    # DRF URLs
    path('', include('comments.urls_api')),
    path('', include('accounts.urls_api')),
    path('', include('posts.urls_api')),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]


if settings.DEBUG:
    urlpatterns = (
        urlpatterns + static(
            settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

newsfeeds/views.py
"""Views for `newsfeeds` app."""

from actstream.models import user_stream
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.contenttypes.models import ContentType
from django.views.generic import ListView

from accounts.models import Profile


class NewsFeedListView(LoginRequiredMixin, ListView):
    """ListView containing `user_stream` instances."""

    template_name = 'newsfeeds/list.html'
    context_object_name = 'feeds'
    paginate_by = 50

    def get_queryset(self):
        """Returns listview's queryset."""
        # use `actstream.user_stream` as the listview queryset
        usr_stream = user_stream(
            self.request.user).prefetch_related('actor', 'action_object')

        return usr_stream

newsfeeds/templates/newsfeeds/list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Newsfeeds{% endblock %}

{% block css %}
.streams-container {
  margin-top: 70px;
  margin-left: auto;
  margin-right: auto;
}
.card-feeds {
    margin-top: 0.5em !important;
    margin-left: auto;
    margin-right: auto;
    border-radius: 5px !important;
    display: block;
}
.streams-container > .alert {
  max-width: 500px;
  margin: 2em auto auto auto;
}
{% endblock css %}

{% block content %}
<div class="streams-container">
    {% if not feeds %}
    <div class="alert alert-info col-md-8" role="alert">
      <strong>Nothing to display.</strong><br/>
      You're not following any post or user. <a href="#search_field" class="alert-link">Search</a> and add friends to start.
    </div>
    {% endif %}
    {% for feed in feeds %}
      <div class="card card-feeds pt-2 pb-2 col-lg-7 col-lg-offset-3 col-md-10 col-md-offset-1 d-block">
        <div class="row">
          <div class="col-2 col-sm-1 col-md-1 col-lg-1">
              <i class="fas fa-user-tie mt-3"></i>
          </div>
          <div class="col-10 col-sm-11 col-md-11 col-lg-11 pt-2">
            <a href="{% url 'accounts:profile' slug=feed.actor.profiles.slug %}"><strong>{{ feed.actor.profiles.first_name }} {{ feed.actor.profiles.last_name }}</strong></a>
              <strong> {{ feed.verb }}
                {% if feed.target.profiles %} 
                  <a href="
                    {% if feed.target.id == user.id %}
                      {% url 'accounts:my-profile' %}
                    {% else %}
                      {% url 'accounts:profile' slug=feed.target.profiles.slug %}
                    {% endif %}"
                  > {{ feed.target.profiles.first_name }} {{ feed.target.profiles.last_name }}</a>
                {% endif %}
              </strong>
            {% if feed.action_object.content %}
              <hr />
              <p>{{ feed.action_object.content|safe }}</p>
            {% endif %}
            <hr />
            <small class="text-muted">{{ feed.timestamp|timesince }} ago</small>
            {% if feed.action_object.content %}
              <a href="" class="float-right">Read more...</a>
            {% endif %}
          </div>
        </div>
      </div>
    {% endfor %}
    {% if not page_obj.paginator.num_pages == 1 %}
      <div class="card card-feeds pt-2 pb-2 col-lg-7 col-lg-offset-3 col-md-10 col-md-offset-1">
        <div class="text-center">
          <span>
            {% if page_obj.has_previous %}
              <a class="btn btn-info btn-sm" href="?page=1">&laquo; first</a>
              <a class="btn btn-info btn-sm" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
            {% endif %}
            <a class="btn btn-info btn-sm active">{{ page_obj.number }}</a>
            {% if page_obj.has_next %}
              <a class="btn btn-info btn-sm" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
              <a class="btn btn-info btn-sm" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
          </span>
        </div>
      </div>
    {% endif %}
</div>
{% endblock content %}